"""
COVID-19 Mortality Analysis — Visualisation

Author  : Anwar Nafidi
Input   : CSVs generated by data_processing.py
Output  : 3 charts saved to /outputs
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


# 1. LOAD PROCESSED DATA:

last_by_country    = pd.read_csv("data/last_by_country.csv")
continents_compare = pd.read_csv("data/continents_compare.csv", index_col=0)
evolution          = pd.read_csv("data/evolution_4_countries.csv")

# Ensure date column is parsed as datetime for correct time-axis rendering
evolution["date"] = pd.to_datetime(evolution["date"])


# 2. CHART 1 — Top 10 countries by mortality rate

top10 = (
    last_by_country
    .sort_values("mortality_rate", ascending=False)
    .iloc[:10]
)

plt.figure(figsize=(9, 5))
plt.barh(top10["location"], top10["mortality_rate"], color="#C84B31")
plt.gca().invert_yaxis()          # rank 1 at the top
plt.xlabel("Case-fatality rate (%)")
plt.ylabel("Country")
plt.title("Top 10 Countries by COVID-19 Mortality Rate")
plt.tight_layout()
plt.savefig("outputs/chart1_top10_mortality.png", dpi=150)
plt.show()


# 3. CHART 2 — Continent comparison (side-by-side subplots)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("COVID-19 Impact by Continent", fontsize=13, weight="bold")

# Left: deaths per million
axes[0].bar(continents_compare.index, continents_compare["deaths_per_million"], color="#185FA5")
axes[0].set_title("Average Deaths per Million")
axes[0].set_xlabel("Continent")
axes[0].set_ylabel("Deaths / 1M inhabitants")
axes[0].tick_params(axis="x", rotation=45)

# Right: case-fatality rate
axes[1].bar(continents_compare.index, continents_compare["mortality_rate"], color="#1D9E75")
axes[1].set_title("Average Case-Fatality Rate")
axes[1].set_xlabel("Continent")
axes[1].set_ylabel("Mortality rate (%)")
axes[1].tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.savefig("outputs/chart2_continents.png", dpi=150)
plt.show()


# 4. CHART 3 — 7-day rolling deaths evolution by country


COUNTRIES = ["Morocco", "Spain", "France", "Germany"]
COLORS    = ["#1D9E75", "#D85A30", "#185FA5", "#7F77DD"]

plt.figure(figsize=(12, 5))

for country, color in zip(COUNTRIES, COLORS):
    subset = evolution[evolution["location"] == country]
    plt.plot(subset["date"], subset["new_deaths_7d"], label=country, color=color, linewidth=1.8)

# Format x-axis as readable dates
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=6))
plt.setp(plt.gca().xaxis.get_majorticklabels(), rotation=30, ha="right")

plt.xlabel("Date")
plt.ylabel("New deaths (7-day average)")
plt.title("COVID-19 Daily Deaths — 7-Day Rolling Average")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/chart3_evolution.png", dpi=150)
plt.show()

print("All charts saved to /outputs")
